### ISSUE TITLE
As CORE-ENGINE, there needs to be a way to execute rule CG0173

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#116]
Refer to JIRA ticket: https://jira.cdisc.org/browse/CORERULES-149

The Rule needs to be able to do the following:

Scope: FA
Sensitivity: Record
Given an FA record:
Check if the "FATEST" variable value matches the "label" of a variable within the list of CDISC Library Model Variables where "role" ends in "Qualifier".
If it does match, check if the "FATESTCD" variable value matches the corresponding "name" in the same CDISC Library variable.

**Comment by nhaydel** [comment]
@gerrycampion @nickdedonder my thoughts on how we can write this rule to use operations/operators that either exist or are generic enough to be useful elsewhere:

Write one or more operations that returns the library variable metadata for a variable referenced in a reference column. Ex. given the dataset:

| FATESTCD | FATEST             |
|--------|----------------------|
| OCCUR  | Occurence Indicator |
| SEV    | Severity/Intensity   |
| TOXGR  | Toxicity/Grade       |

The operation:
```yaml
Operations:
  - id: $referenced_variable_metadata
    name: FATEST # column that references a variable
    operator: label_referenced_variable_metadata
```

The resulting dataset would be:

| FATEST | FATESTCD             | $referenced_variable_metadata_name | $referenced_variable_metadata_role | $referenced_variable_metadata_type (etc) |
|--------|----------------------|------------------------------------|------------------------------------|------------------------------------------|
| OCCUR  | Occurrence Indicator | --OCCUR                            | Record Qualifier                   | Char                                     |
| SEV    | Severity/Intensity   | --SEV                              | Record Qualifier                   | Char                                     |
| TOXGR  | Toxicity/Grade       | --TOXGR                            | Record Qualifier                   | Char                                     |

Then the rule check would look something like:

Check:
  all:
    - name: $referenced_variable_metadata_role
      operator: ends_with
      value: "Qualifier"
    - name: FATEST
      operator: not_equal_to
      value: $referenced_variable_metadata_name

**Comment by RamilCDISC** [comment]
### Validation Summary:

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. The Tests were written to verify the changes. The test uses edge test cases and verifies the implementation accurately.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The unit tests were run using the following command
> 	python -m pytest tests/unit/test_operations/test_label_refrenced_variable_metadata.py
> python -m pytest tests/unit/test_operations/test_lname_refrenced_variable_metadata.py
> 
> The regression tests were executed using the following coomnad:
> Python -m pytetst test_cli

### Results:
After successful running of unit, manual and regression tests and careful validation, the issue was found to be good to close

### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
