### ISSUE TITLE
As CORE-ENGINE, I need to fetch a list of timing variables from the library

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#120]
Rule: CG0562
Refer to jira ticket: https://jira.cdisc.org/browse/CORERULES-249

There needs to be a way to get a list of all library variables that have a specified "role" for the given standard. For example, all variables in SDTM that have "role"="Timing"

This could likely be accomplished using an aggregate operator or a predefined variable.

**Comment by htu** [comment]
Moved _get_variable_names_list to base operation.

**Comment by RamilCDISC** [comment]
The QA validation for this issue is complete. The PR successfully adds the required ability mentioned in the Acceptance Criteria. The unit tests are also up to the mark and are good enough to test the functionality. The code changes pass all the unit tests.for reference screenshot is attached. 

<img width="1443" alt="issue 120" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/2f3702ce-bfd6-4b89-a9c1-d476a38c2b8b">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Testing was done to verify the quality of the implementation for the Acceptance criteria. Unit tests were designed to test the made changes using edge cases. All those tests were then run using pytest to verify compliance with acceptance criteria.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Execution:

> The tests were executed in the following order:
> 
> Code Review: The code for all the changes files was reviewed first to check the proper implementation of the Acceptance criteria.
> 
> Unit Tests: The unit tests were run using the following command in the terminal from the root of the project
> python -m pytests path/to/the/test/files.
> Following tests cases were tested:
> 
> 
> Regression Test: The regression testing passed
> 
### Results:
After successful running of unit, Test endpoint rule, regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
