### ISSUE TITLE
Rule blocked: CG0248, SENDIG-72 - Regular expression causes exception when variable is defined as "num"

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#164]
Note that this issue also impacts sdtm rules like CG0248

Applies to e.g. rule SENDIG-72 "value of --DY must be an integer". 
When trying the regex "^-?[0-9]" on the DSDY variable, which is declared as being "num", an exception occurs ""Can only use .str accessor with string values!".

A solution could of course be that there are functions that test
-whether a value is a valid integer
-whether a value is a valid numeric (e.g. float) value.
[unit-test-coreid-SENDIG_72-negative.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/9764048/unit-test-coreid-SENDIG_72-negative.xlsx)

**Comment by JozefAerts** [comment]
Has this ever been fixed?

**Comment by RamilCDISC** [comment]
QA validation part is complete. The Issue is succesfully resolved and rule is no more blocked. The chages were tested against postivie and negative datasets. The positive dataset had all non zero values for the variables DSDY and negative dataset had one string , one zero other than non zero values.
The validation were first conducted on rules editor. We got correct results for both postive and negative datasets. Following image shows output on run against postive dataset

<img width="1306" alt="2" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/fd7bfe0f-022c-4fb7-ac28-f6c20de71df5">

I have also developed regression tests for the issue. The tests use 'test' command from core to validate the postive and negative dataset against the rule. Then it validates that the correct number of errors, in the correct rows and against correct values were recorded. The engine passes the tests. The following image shows the execution of those tests. 

<img width="1507" alt="1" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/d130a229-ec77-49d3-9cdb-e1dde60b6929">


I will create a PR for these regression tests along with others once a number of tests are ready.
