### ISSUE TITLE
not_exists for variable presence only works when there is a second variable check

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#168]
When I have the code:

Check:
  all:
    - name: SPECIES
      operator: not_exists
    - name: USUBJID
      operator: exists

The check works correctly when "SPECIES" is not a column in the dataset.
When I then remove or comment out the last 2 lines (check on USUBJID), I get an error "Output variables: ['SPECIES'] not found in dataset".
It looks as in that case, the validator tries to provide the value of "SPECIES" in the output, but fails, as of course the column is not there - that is what we are testing for.
[SENDIG_105.yaml.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/9776719/SENDIG_105.yaml.txt)
[unit-test-coreid-SENDIG105-negative.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/9776727/unit-test-coreid-SENDIG105-negative.xlsx)

**Comment by gerrycampion** [comment]
From related ticket:
Links to related JIRA Tickets

https://jira.cdisc.org/browse/CORERULES-5852
Rule Information

Standard: SDTMIG
Rule ID: SD1109
Rule Description: Exposure (EX) dataset should be included in every submission.
Describe the bug
Refer to SD1109 and corresponding negative test data.

Rule Type: Domain Presence Check
Check:
  all:
    - name: EX
      operator: not_exists
The issue is that the Domain Presence Check creates a dataframe variable for each dataset that exists in the study. But we are looking for a domain that is missing from the study. So when the check fires an issue, it automatically includes EX as an Output Variable even though it does not exist in the dataframe.

Error returned from Rule Engine

{
"error":"An unknown exception has occurred"
"message":"Output variables: ['EX'] not found in dataset"
}
Expected behavior
There needs to be a way to run this type of rule without an error. One possibility is to provide a default value of "Missing" when an output variable is missing.
