### ISSUE TITLE
Command to query a list of controlled terminology packages in the cache

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#190]
Much like issue #189. We need a way of easily getting a list of available controlled terminology packages from the cache so they can be displayed in our application and passed to the CORE CLI validate command with the correct syntax.

**Comment by nickdedonder** [comment]
**Acceptance Criteria**

- We want to list CT packages in the same format they are accepted in like "sdtmct-2023-03-31"
- The command name should be list-ct
- There should be an option to filter by subset type
- An example would be sdtmct

**Comment by RamilCDISC** [comment]
The issue is ready to be closed and passed from QA review. All the desired changes were successfully implemented.The filtering option also works fine. I will write regression tests for these and add them to github lateron.

<img width="1503" alt="190" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/78e93ca1-935b-493e-9207-262c3625c3e7">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. The rules engine was used to run the command. The command was tested with different filtering options and edge test cases.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The following commands were run to validate manually.
> python -m core list-ct 
> Python -m core list-ct -s sdtmct
> Python -m list-ct -s adtmg
> Python -m list-ct -s adamct

### Results:
After successful running of unit, manual and regression tests and careful validation, the issue was found to be good to closed.


### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
