### ISSUE TITLE
Error handling of non-xpt files

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#196]
If I provide the commandline a data directory `-d` that contains non-xpt files, I get the following error:
`ValueError: Document does not match SAS Version 5 or 6 Transport (XPORT) format`

Often users will want to validate data that exists in the same directory as other study files.

Acceptance criteria:
- If a directory contains files that have a non-supported data file extension (.xpt for now), do not throw an error. Instead, provide a list of files included and excluded from validation in the CORE Report Conformance Details
- If a directory contains files that have a supported data file extension, but the file is not in the correct format, then an error should be thrown. For example, if a file has a ".xpt" extension, but it cannot be parsed as an xpt file.

**Comment by JozefAerts** [comment]
The define.xml seems to be accepted, but other file types .pdf (like the annotated PDF), .xsl (like the stylesheet) and .html (like the rendering of the define.xml) cause the validator to complain about non-XPT and then stop.

**Comment by JozefAerts** [comment]
Maybe this is the reason (run_validation.py) ...
![snapshot](https://user-images.githubusercontent.com/25853332/201320289-ef95119b-d6a0-488e-8d4e-29ec6f02f542.png)

**Comment by nhaydel** [comment]
> Maybe this is the reason (run_validation.py) ...
> ![snapshot](https://user-images.githubusercontent.com/25853332/201320289-ef95119b-d6a0-488e-8d4e-29ec6f02f542.png)

That is why define xml files are accepted. This is a relatively simple fix to handle other files as well. Feel free to make a PR if you want to take care of this issue

**Comment by JozefAerts** [comment]
Thanks Nic!
   What is a "PR"?
   
   I am not that good in Python yet that I want to start writing/adapting CORE code. Maybe in the following weeks (still learning Python...).
   What I meant with the screenshot is that it looks as the current code selects all files that are not define.xml files. I think it should just be the other way around (only accept .xpt files) OR that it excludes PDF, HTML, ... files.
   It could also be coded so that depending on the format provided, it selects all .xpt files, or all .json files (for Dataset-JSON), or all .xml files (for Dataset-XML, except for the define.xml).
   Another way would be to add a "try-catch" so that files that cannot be parsed are just skipped. I think the latter could be the best solution.
   
   
   
  
    
   
  
   With best regards,
   Jozef
   
   
   
    Nic ***@***.***> hat am 11.11.2022 12:53 CET geschrieben:
    
   
     
    
   
     
    
     
    
    Maybe this is the reason (run_validation.py) ... 
    
   That is why define xml files are accepted. This is a relatively simple fix to handle other files as well. Feel free to make a PR if you want to take care of this issue

**Comment by nhaydel** [comment]
@JozefAerts a PR is a pull request.

**Comment by nhaydel** [comment]
@JozefAerts I see you are working on handling dataset json. I will handle this issue
