### ISSUE TITLE
As VALIDATOR, I want to cross-check dataset variable against individual MedDRA components so that I can stay compliant with SD0008/SD0008C, SD1114/SD1114C, SD2007, SD2009, SD2010/SD2010C, SD2011, SD2012/SD2012C, SD2013, SD2014, SD2015, SD2016

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#261]
1. This check only applies to SDTM and SEND data. ADaM has different implementation for MedDRA variables.
2. This check is IG-version-agnostic.
3. This check takes the MedDRA version from the define.xml.
4. This check does not take MedDRA hierarchy into consideration.

SD0008 in FDA VR v1.6:
- Rule message: Value for --DECOD not found in MedDRA dictionary
- Rule description: Value for the Dictionary-Derived Term (--DECOD) variable must be populated using a Preferred Term of the MedDRA dictionary of a version specified in the define.xml (Case-insensitive).

Relationship between variable and MedDRA component:

- SD0008: --DECOD against Preferred Term
- SD0008C: --DECOD against Preferred Term (Case sensitive)
- SD1114: --BODSYS against System Organ Class
- SD1114C: --BODSYS against System Organ Class (Case sensitive)
- SD2007: --PTCD against Preferred Term Code
- SD2009: --LLTCD against Lowest Level Term Code
- SD2010: --HLT against High Level Term
- SD2010C: --HLT against High Level Term (Case sensitive)
- SD2011: --HLTCD against High Level Term Code
- SD2012: --HLGT against High Level Group Term
- SD2012C: --HLGT against High Level Group Term (Case sensitive)
- SD2013: --HLGTCD against High Level Group Term Code
- SD2014: --BDSYCD against Body System or Organ Class Code
- SD2015: --SOC against System Organ Class
- SD2015C: --SOC against System Organ Class (Case sensitive)
- SD2016: --SOCCD against System Organ Class Code

**Comment by gerrycampion** [comment]
Note that this is also blocking CDISC SDTMIG Meddra rules

**Comment by RamilCDISC** [comment]
I ran a test validation using the dataset and rule file provided in the connected PR. The engine outputs an error while executing the rule. the error says:[ERROR 2023-08-16 17:02:16,871 - console_logger.py:47] - Error occurred during validation. Error: 'NoneType' object has no attribute 'lower'. Error message: 'NoneType' object has no attribute 'lower


Due to error rule is being skipped and not executed. Please see the attached screenshot for further reference. 

<img width="1476" alt="Screen Shot 2023-08-16 at 4 59 17 PM" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/83d3ed8a-711a-43c3-b0ec-7f7ea78d5ba7">
