### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against my study for values not found in user-defined codelist so that I can stay compliant with SD0037

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#273]
1. This check applies to SEND, SDTM, and ADaM data.
2. This check is IG-version-agnostic.
3. User-defined codelist means no `CodeList/Alias[@Name]`. For Define-XML v2.1, `def:IsNonStandard="Yes"`.
4. For variables in a study dataset that use a user-defined codelist, all the distinct values need to appear in the study define.xml.
5. This check is similar to SD1228, but specific to values at the dataset level.

SD0037 in FDA VR v1.6:
- Rule message: Value for variable not found in user-defined codelist
- Rule description: Variable values should be populated with terms found in the user-defined codelist associated with the variable in define.xml.

**Comment by nhaydel** [comment]
Option 3:

STUDYID USUBJID AESEQ  NEW...$user_defined_codelists
1         a      "ADD"  "C"  {AESEQ: ["ADD"..], "NEW": [..]}
1         a      "ADD"  "C"
1         a      "ADD"  "C"
1         a      "ADD"  "C"
1         a      "ADD"  "C"
1         a      "ADD"  "C"

Check:
   - name: AESEQ
     operator: is_contained_by - would need to be modified to pull out the target from the value if value is dictionary
     value: $user_defined_codelists

**Comment by RamilCDISC** [comment]
The QA review for this issue is complete. The changes were tested by making all variables present in the define xml and also deliberately missing out variables. The missing one was reported as negative cases. This fulfills the acceptance criteria. The issue is good to close.

<img width="1471" alt="273 a" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/d7c71f30-3dc5-4872-93f1-eb5af1cb9273">

<img width="1483" alt="273 b" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/15157456-affa-4339-af0f-118f93555a27">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. Unit tests were designed to test the made changes using edge cases. All those tests were then run using pytest to verify compliance with acceptance criteria.

**Test Endpoint:** 
A rule was written using the logic provided in the PR related to this issue and then tested against dataset files having both positive and negative cases regarding the implementation.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations
- 

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Execution:

> The tests were executed in the following order:
> 
> **Code Review:** The code for all the changes files was reviewed first to check the proper implementation of the Acceptance criteria.
> 
> **Unit Tests:** The unit tests were run using the following command in the terminal from the root of the project
> python -m pytests path/to/the/test/files
> **Test Endpoint:** Rule logic matching to the one in PR was written to test the implementation using the endpoint
> Dataset having one negative test case was used against this issue. The negative case was successfully identified by the endpoint. This showed that the endpoint is able to successfully identify and separate negative cases from all other cases.
> 
> **Regression Test:** Regressions tests were run in the end

### Results:
After successful running of unit, Test endpoint rule, regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.





### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
