### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against my study for values in VLM not found in user-defined codelist so that I can stay compliant with SD1228

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#274]
1. This check applies to SEND, SDTM, and ADaM data.
2. This check is IG-version-agnostic.
3. User-defined codelist means no `CodeList/Alias[@Name]`. For Define-XML v2.1, `def:IsNonStandard="Yes"`.
4. For variables in a study dataset that use a user-defined codelist, all the distinct values need to appear in the study define.xml.
5. This check is similar to SD0037, but specific to values in value-level metadata.

SD1228 in FDA VR v1.6:
- Rule message: Variable value not found in user-defined codelist when value-level condition occurs
- Rule description: Variable value must be populated with terms from user-defined value level codelist as specified in define.xml file.

**Comment by RamilCDISC** [comment]
The validation for this issue is completed. The implementation and code changes are good enough to complete the acceptance criteria. The testing also passed for the issue as it successfully found the negative cases. See attached screenshot for reference.

<img width="1459" alt="274" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/127795dd-8dfa-4023-b70f-2b278ae7c7e9">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. Unit tests were designed to test the made changes using edge cases. All those tests were then run using pytest to verify compliance with acceptance criteria.
**Test Endpoint:** 
A rule was written using the logic provided in the PR related to this issue and then tested against dataset files having both positive and negative cases regarding the implementation.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The tests were executed in the following order:
> 
> **Code Review:** The code for all the changes files was reviewed first to check the proper implementation of the Acceptance criteria.
> 
> **Unit Tests:** The unit tests were run using the following command in the terminal from the root of the project
> python -m pytests path/to/the/test/files
> **Test Endpoint:** Rule logic similar to mentioned in PR was written to test the implementation using the endpoint
> Dataset having two negative test cases was used against this issue. The negative case was successfully identified by the endpoint. This showed that the endpoint is able to successfully identify and separate negative cases from all other cases.
> 
> **Regression Test:** In the end regression tests were executed

### Results:
After successful running of unit, Test endpoint rule, regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.


### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
