### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for inconsistent use of def:IsNonStandard attribute for standard domains or datasets so that I can stay compliant with CG0312

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#302]
Condition: Custom domain present in study
Rule: DOMAIN not in reserved or modelled standard

This check only applies to Define-XML v2.1.

Custom domain is defined to be when `ItemGroupDef[@def:IsNonStandard]` is set to  "Yes".

DOMAIN reserved means domain names begin with 1) those listed on the CDISC CT DOMAIN (C66734); 2) AD, AP, AX, SA, SQ (Pg. 14 of the SDTMIG v3.4).

Modeled standard means domains names in the corresponding SDTM and SDTMIG.

Conversely, when a domain name beings with X, Y, or Z, it checks `ItemGroupDef[@def:IsNonStandard]` must be set to  "Yes".

**Comment by gerrycampion** [comment]
https://jira.cdisc.org/browse/CORERULES-32

**Comment by RamilCDISC** [comment]
Everything works as expected, unit tests also pass and are good enough to test the changes. The changes were also tested using the rule editor. The issue is clear from the QA Validation point. Attached screenshot for the reference. 

<img width="902" alt="302 1" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/c71f6637-c049-435e-a4f5-a2f2c35933d7">

<img width="1507" alt="302 2" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/0c5b2ea6-7d79-43f8-92eb-02cf7faace0e">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. The rule editor was used to do the manual testing. Appropriate file were passed to rule editor and response was collected verify the implementation.
**Unit Testing:**
Unit tests were written for the changed code files, covering the edge test cases. The unit tests were run to see if the changes are in accordance with the Acceptance criteria.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Execution:

> The following commands were run to validate manually.
> python -m pytetst path/to/the/test_rule_engine.py
> The manual tests were run on the rule editor.

### Results:
After successful running of unit, manual and regression tests and careful validation, the issue was found to be good to close.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
