### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for non-collected or derived --DUR so that I can stay compliant with CG0002, CG0015

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#304]
Condition: --DUR ^= null
--DUR collected and not derived

--DUR ^= null means the variable is present and has at least 1 non-null value.

For Define-XML v2.0: For the --DUR variable, the associated `ItemDef/def:Origin[@Type]` is set to "CRF".
For Define-XML v2.1: For the --DUR variable, the associated `ItemDef/def:Origin[@Type]` is set to "Collected".

P.S. Not meant to iterate all --DUR records.

Acceptance Criteria:
- New rule type created that returns the DefineVariablesMetadataDataset
- Be able to support a rule with the following logic:
```
Option 2:

Rule Type: # Newly created rule type for getting define variables metadata
Check:
 name: define_variable_is_collected
 operator: equal_to
 value: false
 name: dur_variable_name
 operator: equal_to
 value: --DUR
 name: $dur_is_not_null
 operator: equal_to
 value: true

Operations:
  - id: $dur_is_not_null
    name: --DUR
    operator: is_not_null # Return true if at least one record is non null

```

**Comment by RamilCDISC** [comment]
I have reviewed the code and tests in the related PR. The changes seems to solve the issue and acceptance criteria is met. All tests ran successfully.

<img width="1511" alt="304" src="https://user-images.githubusercontent.com/113539111/234117285-e03eb765-78ee-4aa7-b568-84392ce24b92.png">

**Comment by RamilCDISC** [comment]
### Validation Summary
### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

**Unit Testing:**
Unit tests were written for the changed code files, covering the edge test cases. The unit tests were run to see if the changes are in accordance with the Acceptance criteria.
### Code Review:
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The following commands were run to validate manually.
> python -m pytetst tests/unit/test_define_xml_reader.py
> python -m pytest tests/unit/test_operations/test_variable_is_null.py
> The regression tests were run using the command
> python -m pytest test_cli.py

### Results:
After successful running of unit and regression tests and careful validation, the issue was found to be good to close.


### Deviations and Non-conformances:
Following slight deviation was made during development/coding part as mentioned by developer in the PR

> I deviated slightly from the issue by creating variable_is_null instead of is_not_null to reduce confusing double negatives.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
