### ISSUE TITLE
Data location not showing all datasources in report's Conformance Details

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#314]
To reproduce, run a validation with more than 5 datasets. For example, I used the msg 2.0 datasets.
Navigate to the Conformance Details tab in the report spreadsheet and view the Data Location cell.

The cell only provides the first 5 datasets.

**Comment by nhaydel** [comment]
Only showing 5 files is a decision we made earlier in development, we thought it would be best to limit the number of files shown in case a ton are shown. If we want to change that I think it should be a separate issue with actual acceptance criteria from Nick

**Comment by gerrycampion** [comment]
@nickdedonder I think it would be important to show all files that are validated. The report doesn't show any other traceability of what was actually validated, especially if the datasets pass validation.
It would probably be more useful to have each file path in a different row and include other details about the file, like timestamp, size, dataset label, etc.

**Comment by RamilCDISC** [comment]
I did not find a specifically mentioned AC for the issue but what from above conversations i get is that the datasets which are validated must be lodged into the report generated, when a validation is run. I ran the validation against more than 5 datasets and the report was successfully generated but the datasets path/names were not written in the report as seen in the screenshot.


<img width="1483" alt="314" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/97f31675-7582-4fd1-8d18-1f86ceaafbe8">

**Comment by nhaydel** [comment]
@RamilCDISC This issue should be closed. It is handled in the issues mentioned above that have not been worked on yet

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. The rules engine wasto generate reports against different datasets.


- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The following commands was run to validate manually.
> python -m core validate -s sdtmig -v 3.4 -d path/to/clean/datasets
> python -m core validate -s sdtmig -v 3.4 -d path/to/Issue/datasets

### Results:
After generation of reports it was noted that the AC was not implemented properly. This was reported above by QA. Later on it was made clear that this issue can be closed because the implementation of AC will be handled in another issue.

### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process did not pass successfully, indicating that the system do not functions as intended and does not meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
*
