### ISSUE TITLE
Test data causing 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#320]
Test steps:
Test with the following rule and data:
[SEND2.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/10994295/SEND2.json.txt)

The 500 message is returned:
"An unhandled exception occurred. 'NoneType' object has no attribute 'get'"

I'm not sure whether this is an endpoint issue or engine issue.
The issue seems to be caused by the dataset, not by the rule.

**Comment by nhaydel** [comment]
I assume this is caused by the variables array in the datasets having a bunch of nulls.

**Comment by nickdedonder** [comment]
AC
Test endpoint should properly notify the user of malformed data

**Comment by RamilCDISC** [comment]
The issue is successfully validated. The AC is fully met. A proper message explaining the errors in the dataset in returned when POST request are made. This fulfills the AC making the issue ready to close. Please see attached screenshot for reference

<img width="1268" alt="320" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/78050f21-d971-4997-b654-5ab84c4e7252">
