### ISSUE TITLE
Reporting template enhancement

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/cdisc-rules-engine#324]
The reporting template has been updated to include the following enhancements:

**Issue Summary**

- RuleId has been updated to CORE-ID
- Severity has been deleted

**Issue Details**

- RuleId has been updated to CORE-ID

**Conformance Details**

- Bundle details header has been changed to Standards Details
- CORE Engine Version has been added

[report-template-update.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11080424/report-template-update.xlsx)

**Comment by nickdedonder** [comment]
The reporting template has been updated to include the following enhancements:

**Issue Summary**
- RuleId has been updated to CORE-ID
- Severity has been deleted

**Issue Details**
- RuleId has been updated to CORE-ID

**Conformance Details**
- Bundle details header has been changed to Standards Details
- CORE Engine Version has been added

**Comment by nhaydel** [comment]
@nickdedonder the template provided also includes modified timestamp and dataset size. Will those be handled in another issue? If not that changes the pointing of this issue

**Comment by nhaydel** [comment]
@nickdedonder @chowsanthony we have decided that considering the acceptance criteria, the dataset details tab will be left blank until #314 is completed

This issue will only ensure the updates outlined above are included in the report

**Comment by RamilCDISC** [comment]
I have thoroughly tested the changes by generating reports against valid and invalid datasets. Reports were generated using the validate and Test command of core.py file. Following are the screenshots for the commands ran:

python -m core validate -s sdtmig -v 3.4 -dp "C:\Users\stsam\Desktop\CDISC-CORE\Clean\xpt\ae.xpt"
![image](https://user-images.githubusercontent.com/113539111/230199651-814e78a9-e726-40ee-8769-1a6ecb11f72f.png) 


python -m core validate -s sdtmig -v 3.4 -dp "C:\Users\stsam\Desktop\CDISC-CORE\Issues\xpt\ae.xpt"
![image](https://user-images.githubusercontent.com/113539111/230199742-32b325c6-4f23-48f1-9905-c8d234238064.png) 


python core.py test -s sendig -v 3-1 -r "C:\Users\stsam\Desktop\CDISC-CORE\SENDIG_266_rule.json.txt"		 -dp "C:\Users\stsam\Desktop\CDISC-CORE\SENDIG_266_negative_testdata_datasets.json.txt"
![image](https://user-images.githubusercontent.com/113539111/230199809-8b8ea962-230b-4b42-b5d2-345916134ff3.png) 

Reports are also attached for reference.

**Conclusion:** The acceptance criteria for this issue is successfully fulfilled. The issue can be closed.

**Generated Reports:**

[CORE-Report-2023-04-06T00-48-26-InvalidDataset.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11162756/CORE-Report-2023-04-06T00-48-26-InvalidDataset.xlsx)
[CORE-Report-2023-04-06T00-51-19-validDataset.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11162757/CORE-Report-2023-04-06T00-51-19-validDataset.xlsx)
[CORE-Report-2023-04-06T00-45-40-sendig.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11162758/CORE-Report-2023-04-06T00-45-40-sendig.xlsx)

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included
**Manual Testing:**
A manual testing was done and three reports were generated, to validate the changes in the report. Two reports were generated using validate command of core.py file in the Rule Engine and one was generated using test command of the same file. The three reports can be downloaded using the links in above QA comments:

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Cases:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6f81b70b-7fff-6fb5-9c28-8bdecd9ee81f"><div dir="ltr" style="margin-left:0pt;" align="left">

Test Case Description | Function Name | Expected Result | Result
-- | -- | -- | --
Validate the generated report using validate command | validate | Expected result: Report with changes as described in AC | Passed
Validate  the generated report using the test command | test | Expected result:Report with changes as described in AC | Passed

</div></b>
### Test Execution:

> The Tests were run by executing the manual test. Following command was run for execution of tests:
> python -m core validate -s sdtmig -v 3.4  -dp  path/to/datasetfile_1
> python -m core validate -s sdtmig -v 3.4 -dp path/to/datasetfile_2
> python -m core test -s sdtmig -v 3.4 -r path/to/rule/file -dp path/to /datasetfile

> 
> The regression tests were executed using the following command:
> Python -m pytest test_cli.py

### Results:
After successful running of manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results**: All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
