### ISSUE TITLE
Test Endpoint support rules involving Library Standards and Codelists

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#333]
### Acceptance criteria
- Library standards and code lists metadata are available
- A single version of the IG standard should be provided
- A list of CT package versions should be provided

**Comment by RamilCDISC** [comment]
Me and developer @nhaydel worked on this one but were unable to find a way to run the azure function locally, I will end review on this issue as soon as we are able to get to run the function from azure locally.

**Comment by RamilCDISC** [comment]
The code modifications pertaining to this matter have undergone a comprehensive review process. The alterations effectively adhere to the Acceptance Criteria (AC) defined for this particular issue. Furthermore, manual testing has been conducted, employing a JSON payload that encompasses the necessary standards and an array of code lists. The payload has been meticulously designed to align with the specified acceptance criteria requirements. As a result of this testing, successful responses were obtained when utilizing POST commands. Visual evidence of these successful responses can be observed in the accompanying screenshot.

Consequently, the issue has successfully passed the quality assurance validations and is now ready for closure.
<img width="1265" alt="333" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/1d10b647-064d-4485-b30b-66095e2f476f">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. A JSON payload with necessary requirements were sent to the rules engine, and the responses were checked to verify proper working.

**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The Tests were run manually by sending a JSON payload using insomnia. The recommended checking was running the system locally, But QA computer architecture was not supported by azure functions, for local running. 
> To cope with this, tests were run using the azure web deployment.


### Results:
After successful running of manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
