### ISSUE TITLE
Move Rule Schema from Rules Editor to Core Rules Engine repo

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#335]
AC
- Rule schema has been moved from Rules Editor to Core Rules Engine
- Rule Editor accesses the rule schema from the github file on the main branch of the CORE Engine

*Note: There is a chance this may not work if it is a requirement that the schema exists on the same domain (similar to CORS issues)

**Comment by RamilCDISC** [comment]
The Acceptance criteria for this Issue is met, but while following the steps in the PR related to this issue, it is found that the intellisense doesn't work on pressing ctrl/command + space but only when space is pressed after entering a colon.

**Comment by gerrycampion** [comment]
> The Acceptance criteria for this Issue is met, but while following the steps in the PR related to this issue, it is found that the intellisense doesn't work on pressing ctrl/command + space but only when space is pressed after entering a colon.

@RamilCDISC are you using Windows, Mac, or Linux?
Here is more info about the intellisense: https://code.visualstudio.com/docs/editor/intellisense

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. The Rule editor was checked for all the changes that have been incorporated, one by one, using different methods and edge cases. 
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:
The manual tests were conducted on the rule editor. All the changes mentioned in the connected PR were checked and tested rigorously using, edge test cases manually.
### Results:
After successful running of unit, manual and regression tests and careful validation, the issue was found to be good to close but it was noted that the options drop box did not appear with ctrl/command + space but with only space after a colon. Upon investigation it was found that it is due to the different platform from where the rule editor was being accessed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
Test Results: All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
