### ISSUE TITLE
As a Rule Author, I want my SDTM rule to be written automatically

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/cdisc-rules-engine#373]
- Read rule definition from SDTM_V2_0: SDTM and SDTMIG Conformance Rules_v2.0
- Get rule statistics if get_db_rule or pub2db is enabled.
- Back up current rule(s)
- Get existing rule if the rule exists in the database or in local rule folder
- Check rule citation agaist rule definition
- Add missing citations to the rule
- Write the rule to target folders in JSON and YAML formats
- Publish the rule to the database if pub2db is enabled

**Comment by RamilCDISC** [comment]
The review for the crbuilder is done. All the acceptance criteria is fulfilled. Tests were run against all the SDTM_2.0 rules. One of the log files is attached for reference. It can be seen in the log file that the rule builder is performing all the steps which are required in acceptance criteria.

Following is one of the command used to run the tests for the crbuilder class.

python rulebuilder.py process --r_ids all  --pub2db 1




[CG0001-J144826.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11356181/CG0001-J144826.txt)



[job-J144826-stat.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11356207/job-J144826-stat.xlsx)


[CG0001-Draft.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11356227/CG0001-Draft.txt)

Following json and yaml files are the rules file written automatically by the rule builder

[CG0001-Draft.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11356255/CG0001-Draft.json.txt)

[CG0001-Draft.yaml.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11356258/CG0001-Draft.yaml.txt)

**Comment by RamilCDISC** [comment]
Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria on rule builder repository.. The Rule builder was verified to see if all requirements of AC are implemented and are working fine
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Execution:

> The tests were run using the following command:
> python rulebuilder.py process --r_ids all --pub2db 1
> The regression tests were executed using the following command:
> Python -m pytest test_cli.py


### Results:
After successful running of unit and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability
