### ISSUE TITLE
Flag to specify Define-XML file

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#382]
The engine currently has no way to accept Define-XML files if the user is passing the datasets individually instead of providing a folder. As our app only passes datasets individually it'd be good to have a new flag such as "-dp" to specify the Define-XML file path to be used.

**Comment by nhaydel** [comment]
@mdeforestbrown currently the engine assumes the define.xml file is in the same directory as the data. So in the case where a directory is specified, the engine infers the location of the define.xml. However, in the case where data files are specified individually, the engine needs some way to know where the define is. I think there are two ways to handle this:

1. Assume the files specified are all in the same location and just use the directory of one of the files
2. Provide a way for users to specify where the define.xml file is located using a command line flag. This solution requires more code changes, but would allow for data files to be in separate locations

**Comment by nhaydel** [comment]
@htu the behavior in the test function is currently intentional. I don't think we should add to the work required for this issue. If we want to address the behavior in the test function it should be a new issue

**Comment by mdeforestbrown** [comment]
@nhaydel That makes sense, great thanks for your input that should be enough for me to get going.

**Comment by JozefAerts** [comment]
During development of the datasets, a user may have more than 1 "define.xml", for example, as the user is developing datasets individually (e.g. per domain), with the "the define.xml" "stearing" the mapping.
For example, during development, a user may have a define_DM.xml, a define_AE.xml, a define_CM.xml etc.. These even't don't have to be in the same folder as where the (development) XPT files reside.
So, a flag like "-df" ("define file location") would be very useful.
IMO, we shouldn't limit the use of CORE to the case where the datasets and the define.xml are "submission-ready".

**Comment by RamilCDISC** [comment]
I found two issue while validating the implementation:

1. **Missing required positional arguments error while running a test validation**
The engine outputs a missing required arguments error when running a test validation with or without dxp (flag for define xml path). I have attached a screenshot showing the error and also test files in the zip folder. 
<img width="973" alt="Screen Shot 2023-07-31 at 5 42 41 PM" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/b8ea12ae-90b5-43a4-844f-83a21c3a94d5">


2. **Incorrect Define version in the generated report**
Incorrect define version was observed in the report while running a validation using validate command. The report shows define version 2.1 although a define of version 2.0 was passed to dxp flag. I have attached screenshot and report for reference. 

<img width="984" alt="Screen Shot 2023-07-31 at 5 57 01 PM" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/9364ec0a-8c12-4bc5-a8e2-0f238128d1f3">

[Test_files.zip](https://github.com/cdisc-org/cdisc-rules-engine/files/12222879/Test_files.zip)

[CORE-Report-2023-07-31T17-41-07.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/12222884/CORE-Report-2023-07-31T17-41-07.xlsx)

**Comment by nhaydel** [comment]
@mdeforestbrown i can fix this if you are too busy since it will likely block other issues

**Comment by nhaydel** [comment]
@RamilCDISC note the actual test and validation still require that the define file be called define.xml

**Comment by nhaydel** [comment]
@RamilCDISC @mdeforestbrown Put up a PR to fix those issues. Please review: https://github.com/cdisc-org/cdisc-rules-engine/pull/494

**Comment by RamilCDISC** [comment]
Everything works fine now, clear from QA

**Comment by RamilCDISC** [comment]
### VALIDATION SUMMARY
### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. Unit tests were designed to test the made changes using edge cases. All those tests were then run using pytest to verify compliance with acceptance criteria.

**Rules Engine:** 
The rules engine test and validate (in core.py) functionality was utilized to validate proper integration of new flag for passing define.xml path

**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:
The tests were executed in the following order:

**Code Review:** The code for all the changes files was reviewed first to check the proper implementation of the Acceptance criteria.

**Unit Tests:** The unit tests were run using the following command in the terminal from the root of the project
python -m pytests path/to/the/test/files

**Rules Engine:** Validations were performed using test and validate fucntionality of Rules engine. During initial validation it was found that for test functionality engine was throwing a ''Missing Arguments Error''. The error was reported [here:
](https://github.com/cdisc-org/cdisc-rules-engine/issues/382#issuecomment-1659336151). A new PR was created to fix small the issue. Again validations were performed to check if everything and new flag for passing a path for define file works fine.

**Regression Tests:** The regression tests were then run to confirm that the changes in engine did not break any other part of the implementation. New Regression test for this new flag were also created and added through a different PR.

### Results:
After successful running  of unit, Rule Engine test, regression tests and fix of errors found during validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
