### ISSUE TITLE
Deploy rule tester endpoint automatically

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#383]
Currently endpoint deploy can only be triggered manually

AC

- Rule Tester Endpoint is automatically deployed during pr merges to main
- Rule Tester Endpoint can still be triggered manually

**Comment by RamilCDISC** [comment]
The automatic deployment of Rule test endpoint is confirmed and clear from QA. The deployment was confirmed after when i merged the approved PR for QAregression tests. The option of manually running the workflow is also present. Following screenshot shows when the auto deployment was running.

<img width="1453" alt="issue 383" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/741a52b3-22e2-4f12-9a59-edb967251028">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
During the validation of this issue, QA regression tests were also to be pushed to main. So a PR was created to add those tests to the main. The same PR was used to validate the automatic deployment of test endpoint.

### Test Execution:

> The QARegressionTests PR was created and forwarded for approval. After the approval of changes the PR was merged to main. After the merge automatic deployment of the test endpoint was validated. It was also checked if the option to manually deploy the endpoint was still available.

### Results:
After successful merge of QARegressionTest PR, the test endpoint was automatically deployed, this fulfills the first point in the acceptance criteria. The option to manually deploy the endpoint was also available, which fulfilled the second point of the acceptance criteria. Hence the issue was declared clear from validation.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
The deployment of the test endpoint was successfully automated.
The option to deploy the endpoint manually was also still available.
The acceptance criteria for this issue was fulfilled successfully
There were no problems in merging or execution of other automated tasks during merge to main.
