### ISSUE TITLE
Add support for define 2.0

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#390]
AC
- Version of define.xml is extracted from the define.xml file. This will come from:
  /ODM/Study/MetaDataVersion/def:DefineVersion
- Define ODM components will be loaded according to the version. At a minimum, we should support define versions 2.0 and 2.1

Implementation details
There should be an abstract base class for the common define.xml components.
Each version of the define.xml should have its own concrete class that overrides version-specific functionality.

Add following test cases to `test_define_xml_reader.py` `test_define_variable_is_collected`:
```python
test_define_2_0_file_path: str = (
    f"{os.path.dirname(__file__)}/../resources/test_defineV20-SDTM.xml"
)
```

```python
        (
            test_define_2_0_file_path,
            "AE",
            "AEACN",
            True,
        ),
        (
            test_define_2_0_file_path,
            "AE",
            "AEBODSYS",
            False,
        ),
        (
            test_define_2_0_file_path,
            "LB",
            "LBCAT",
            False,
        ),
```

**Comment by RamilCDISC** [comment]
The review for this issue is over. The changes are according to the Acceptance Criteria. The code gets the define xml version from /ODM/Study/MetaDataVersion/def:DefineVersion and ODM components are loaded according to the version. We have separate concrete class for each version and one common abstract base class. This meets with the AC hence passing from QA review. 

Following screenshot shows the successful test runs for the changes.

<img width="567" alt="390" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/dc9dc546-55ce-4978-b7f1-af1850239cb6">

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. All those tests were then run using pytest to verify compliance with acceptance criteria.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:
Following Tests cases were checked against the updated code
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-afb6b5b4-7fff-15f9-0aab-cd4e9de6eb62"><div dir="ltr" style="margin-left:0pt;" align="left">

Test Name | Description | Expected Result | Status
-- | -- | -- | --
test_init_from_filename | Verify if DefineXMLReader can be initialized from a filename | Instance of BaseDefineXMLReader | Passed
test_init_from_file_contents | Verify if DefineXMLReader can be initialized from file contents | Instance of BaseDefineXMLReader | Passed
test_read_define_xml | Verify if DefineXMLReader can read define.xml contents | List of dictionaries containing metadata | Passed
test_extract_domain_metadata | Verify if DefineXMLReader can extract domain metadata | Dictionary containing domain metadata | Passed
test_extract_variable_metadata | Verify if DefineXMLReader can extract variable metadata | List of dictionaries containing variable metadata | Passed
test_extract_variable_metadata_with_has_no_data | Verify if DefineXMLReader can correctly handle variables with no data | Variable metadata indicates no data | Passed
test_define_variable_is_collected | Verify if DefineXMLReader can determine if a variable is collected | Boolean value indicating if variable is collected | Passed
test_extract_value_level_metadata | Verify if DefineXMLReader can extract value level metadata | List of dictionaries containing value level metadata | Passed
test_extract_domain_metadata_not_found | Verify if DefineXMLReader raises an exception for a missing domain | DomainNotFoundInDefineXMLError exception is raised | Passed
test_validate_schema | Verify if DefineXMLReader can validate the schema of define.xml | True if schema validation passes | Passed
test_extract_variable_metadata_not_found | Verify if DefineXMLReader raises an exception for a missing domain in variable metadata | DomainNotFoundInDefineXMLError exception is raised | Passed

</div><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10.5pt;font-family:Arial;color:#1f2328;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&rsquo;</span></p></b><br class="Apple-interchange-newline">

’
### Results:
After successful running of unit, manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results**: All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
