### ISSUE TITLE
Define XML version detection should use namespace only

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#418]
Related to https://github.com/cdisc-org/cdisc-rules-engine/issues/390

Define XML documents can have minor versions in the `DefineVersion` attribute. The version of Define-XML and model package should be determined using the namespace only and not the `DefineVersion` attribute.

AC:
- `DefineXMLReaderFactory._get_define_xml_reader` is updated to retrieve the define version `_from_namespace` only instead of `_from_namespace_version`.
- `version` property is removed from the `DefineXMLVersion` class and corresponding references in the child classes.

**Comment by RamilCDISC** [comment]
The changes in `DefineXMLReaderFactory._get_define_xml_reader` are noteworthy, as it now retrieves the define version from `_from_namespace`. Additionally, the version property has been removed from the `DefineXMLVersion` class and its subclasses. These updates have been confirmed by reviewing the file changes in the connected PR.

With these modifications, all acceptance criteria (AC) for this issue have been met, indicating that it is ready for closure.

While the existing unit tests adequately cover the changes, it is highly recommended to include a dedicated test for validating the define version returned by the updated code. This would further enhance the test coverage and provide greater confidence in the correctness of the implementation.

**Comment by RamilCDISC** [comment]
### VALIDATION SUMMARY
### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

**Unit Testing:**
Unit Testing was done to verify the implementation of the Acceptance criteria. Unit tests were designed to test the made changes using edge cases. All those tests were then run using pytest to verify compliance with acceptance criteria.

**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Results:
### Test Execution:
The tests were executed in the following order:

**Code Review:** The code for all the changed files was reviewed first to check the proper implementation of the Acceptance criteria. It was checked for in the changed files that : 

- DefineXMLReaderFactory._get_define_xml_reader is updated to retrieve the define version _from_namespace only instead of _from_namespace_version
- version property is removed from the DefineXMLVersion class and corresponding references in the child classes

**Unit Tests:** The unit tests were run using the following command in the terminal from the root of the project
python -m pytests path/to/the/test/files

**Regression Tests**: Regression tests were executed to validate that the changes did not break any other part of the code
### Results:
After successful running of unit, Manual,, regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
