### ISSUE TITLE
As a validator I want to see the list of domains that have been validated

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/cdisc-rules-engine#433]
A second tab has been added in the conformance rules report to include all domains instead of showing only 5 on the first tab. The second tab is called Dataset details and contains the following columns:

* Dataset (name of the dataset: ae.xpt)
* Label (long name of the dataset: Adverse Events)
* Location
* Modified Time Stamp (last time an update was made to the dataset
* Size (in kb)
* Number of records
[report-template-update.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11666630/report-template-update.xlsx)

**Comment by nhaydel** [comment]
Location should just contain directory location of the file

**Comment by RamilCDISC** [comment]
I have validated the changes made for this acceptance criteria. I generated reports using validate and test functionality of CORE. The reports generated from the validate function passed the AC check for all test cases (i.e validation with: single dataset, multiple dataset, more than one dataset path). 
However the Reports generated from the test functionality had one problem. The location for the dataset is not correctly reported in these generated reports. As can be observed in the screenshot, instead of a path to the dataset only a dot is present. This behavior was only observed in the reports generated using the test functionality. 

<img width="1496" alt="433 bug" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/883d354b-a7da-47f6-95f7-010b56c3a569">


The generated reports are also attached for reference
[CORE-Report-2023-06-26T13-26-45_SingleDataset.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11872942/CORE-Report-2023-06-26T13-26-45_SingleDataset.xlsx)
[CORE-Report-2023-06-26T13-31-18_MultipleDatasets.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11872943/CORE-Report-2023-06-26T13-31-18_MultipleDatasets.xlsx)
[CORE-Report-2023-06-26T13-33-45_TwoTimesdpOption.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11872944/CORE-Report-2023-06-26T13-33-45_TwoTimesdpOption.xlsx)
[CORE-Report-2023-06-26T13-40-27_TestFunction.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11872945/CORE-Report-2023-06-26T13-40-27_TestFunction.xlsx)
[CORE-Report-2023-06-26T13-47-37_TestFunction.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11872946/CORE-Report-2023-06-26T13-47-37_TestFunction.xlsx)

**Comment by nhaydel** [comment]
@RamilCDISC this is expected due to tests datasets not having a directory in the json

**Comment by RamilCDISC** [comment]
After the clarification, verified datasets. AC is successfully validated and pass from QA.
