### ISSUE TITLE
Dataset-JSON

### ISSUE THREAD

**Issue by dostiep** [cdisc-org/cdisc-rules-engine#439]
Hello,

Now that Dataset-JSON has been added as a new standard on CDISC website, would it be possible to accept Dataset-JSON files instead of the JSON dataset format provided by the rule editor. I don't see the point of having 2 different JSON file format that basically contain the same information.

Thanks

**Comment by JozefAerts** [comment]
I think this is a very good idea!
However, we need to take into account that there is currently now way to generate Dataset-JSON from an Excel file in the rule editor. It should however not be too hard to program that.
The core engine, as far as I know, does not work with Dataset-JSON yet. I made a branch in the past for doing so, but it was never merged into the main branch, as the code did not recognize Dataset-JSON automatically, and my Python code to implement that was insufficient. Also, in the mean time, the Dataset-JSON standard has slightly changed.
IMO, there should clearly be an effort again to accept Dataset-JSON in the CORE engine, especially due to the upcoming Dataset-JSON pilot with the FDA: FDA should be able to validate Dataset-JSON files using CORE.

**Comment by JozefAerts** [comment]
@dostiep: do you have good Python knowledge? I need an "accomplice " for this. 
I could start a new branch for this again, but definitely need help as my Python knowledge is limited.

**Comment by dostiep** [comment]
@JozefAerts I do have Python knowledge. I do have already a Python app to convert SAS/XPT datasets to Dataset-JSON as long as you have an associated Define.xml.

**Comment by JozefAerts** [comment]
Great! I have a similar application XPT=>Dataset-JSON in Java.
I am taking 2-3 weeks off now (I deserve/need it ...) and will then generate a new branch, putting in the old (partial) code I had for Dataset-JSON, and to which you can then contribute. OR: you can create a branch and already start working on it.
I think CORE support will strongly help in acceptance of Dataset-JSON by FDA, and the other way around.

**Comment by dostiep** [comment]
Let's get in touch when you come back then.

**Comment by rradel** [comment]
In the readme file for the rules engine, Dataset-JSON files seem to be accepted but there is an inconsistency about the structure of the json file expected by the engine and the CDISC specifications. Is there a specific reason this is different?

**Comment by JozefAerts** [comment]
I don't think there is.
But the example given in the README is clearly completely outdated.
Can you create a ticket so that that get's corrected (if not already done ;-))?

**Comment by rradel** [comment]
will do, thanks!

**Comment by RamilCDISC** [comment]
QA Validation is complete. In the first review,a minor inconsistency was found. The rules engine worked fine with the xpt dataset even when -df flag was set to json. This inconsistency was removed. In the second review as of now, everything works fine and issue is ready to be closed.
