### ISSUE TITLE
CORERULES-1334 / CG0202: scope skip for RELATIONSHIP class

### ISSUE THREAD

**Issue by marisawyckmans** [cdisc-org/cdisc-rules-engine#576]
`rule_processor.is_relationship_dataset` needs to be revisited to ensure it covers special cases like SQ--
https://github.com/cdisc-org/cdisc-rules-engine/blob/3ed356af70051c917780ee54576e7b0e9df0f640/cdisc_rules_engine/utilities/rule_processor.py#L336

`base_data_service.get_dataset_class` needs to be updated to handle more classes, like `RELATIONSHIP`
https://github.com/cdisc-org/cdisc-rules-engine/blob/3ed356af70051c917780ee54576e7b0e9df0f640/cdisc_rules_engine/services/data_services/base_data_service.py#L143

[CORERULES-1334__CG0202_request.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/13189550/CORERULES-1334_CG0202_request.txt)

**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-1334
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-945

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0202
- **Rule Description**: When QORIG = ASSIGNED, QEVAL should not be null. This rule applies to SUPP- domains in SPECIAL PURPOSE class

**Describe the bug**
When Classes is specified as SPECIAL PURPOSE, the rule is scope skipping the test data, although test data is for SUPP- domains.
![image](https://github.com/cdisc-org/cdisc-rules-engine/assets/138012940/3159e866-b984-4b0d-b48f-498f7b17d72f)
![image](https://github.com/cdisc-org/cdisc-rules-engine/assets/138012940/d9a19325-00de-4e0e-bccd-e2e70a127b0f)

**Error returned from Rule Engine**
{
  "SUPPAE": [
    {
      "executionStatus": "skipped",
      "domain": "SUPPAE",
      "variables": [],
      "message": null,
      "errors": []
    }
  ],
  "SUPPEC": [
    {
      "executionStatus": "skipped",
      "domain": "SUPPEC",
      "variables": [],
      "message": null,
      "errors": []
    }
  ]
}

**Expected behavior**
The rule should not skip SPECIAL PURPOSE class. Perhaps related to #427 ?

Note: when I change Classes to include ALL, the rule works fine.

**Comment by JozefAerts** [comment]
Isn't SUPPxx class "RELATIONSHIP"?
That would declare the behaviour ...

**Comment by apalmercdisc** [comment]
Updated this issue to reflect that it should be RELATIONSHIP rather than SPECIAL PURPOSE; updated the CLASS in Rule Editor for both CG0200 and CG0202 to RELATIONSHIP.

**Comment by RamilCDISC** [comment]
QA validation part is complete. Scope skips issue for Relationship class is fixed. The issue was  validated using rules editor and commandline rules engine both. The engine successfully handles the above mentioned case now. The validation was done using postive and negative test data.

The following screenshot shows one of the successfull run during validation trough rule editor.
<img width="1481" alt="576 1" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/559b9980-3b87-4a5a-8fca-358c51643060">

The following figure shows successful run for the regression tests developed for the issue. The regression tests utilize test command from the core
<img width="1505" alt="576 2" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/2f6f3aa7-cc2b-4eec-94e7-ac13665e14da">

**Comment by drewcdisc** [comment]
Ramil has asked that we do not move this to done until he can finish a PR for some more regression testing that will cover several other tests, including this one.
