### ISSUE TITLE
Rule Editor Test tab validation not working

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#655]
Getting the following exception during "Validate YAML against Schema" in the test tab of the rule editor:
Uncaught (in promise) Error: strict mode: unknown keyword: "optional"

This may either be an issue with the schema in the engine or the updated node version in the editor

**Comment by gerrycampion** [comment]
Issue is in engine caused by addition of this line: https://github.com/cdisc-org/cdisc-rules-engine/blob/6af87aa01edad9ad52a3295b57b822dbec8b8c95/resources/schema/Operations.json#L185

**Comment by RamilCDISC** [comment]
The validation for the issue is complete. Schema validation the rule tab is working fine again. Following test cases were executed for validation:

1. Check schema validation tab when schema is valid
2. Check schema validation tab when schema is invalid
3. Run regression tests to ensure code changes does not affect any other part

The editor properly gives error for the case where schema is invalid: The following screenshot shows one of those cases:

It is recommended that we develop Regression automation for the rule editor , to fasten regression checks

<img width="883" alt="655" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/ad69fc73-9042-4d5e-adc6-4a47d9be9a76">
