### ISSUE TITLE
There needs to be a way to run "CORE Validate" on unpublished rules

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#679]
- Rule data source should be abstract to allow from different locations

There are a few options:
- Cache updater to have a flag to pull unpublished rules
- Allow alternative sources (like local file system)  in json or yaml format

I think ultimately we will want to support both options

**Comment by RamilCDISC** [comment]
While validating the issue I noticed that:
if we  run a validation while not using -lr option and a rule id which is not in the scope of the specified standard, the engine throws an error and exits. You can reproduce using the following command:
`python3 core.py validate -s sdtmig -v 3.4 -dp tests/resources/COREIssue329/ts-test-dataset-T.json -r CORE-000482 -r CORE-000001`

<img width="1222" alt="679 1" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/5fa538b9-7c92-47b5-9c47-3229345769d6">


The other case when -lr is used, the engine gives error in case when the mentioned id is not in the specified local rule directory. You can reproduce using the following command:
`python3 core.py validate -s sdtmig -v 3.4 -lr tests/resources/datasets -dp tests/resources/COREIssue329/ts-test-dataset-F.json -r CORE-000473`

<img width="1211" alt="679 2" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/129048b5-5332-488b-9226-bcff7907b1ba">

Both cases may be fixed in a single change for removing bug.  It is recommended  that there should be graceful exception handling implemented here so even if an error occur, the engine keep validating for the other rules and log the errors

**Comment by SFJohnson24** [comment]
I updated the error handling and the associated test (although it does not need a specific -r flag for -lr in the directory to run) and sent this back to review
